[package]
name = "boba-go"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
thiserror = "2"
ratatui = { version = "0.29.0", default-features = false, features = ["crossterm"] }
crossterm = "0.28"

[[bin]]
name = "boba_tui"
path = "src/bin/boba_tui.rs"
